[server]
maxUploadSize = 20
enableXsrfProtection = true
enableCORS = true

[browser]
gatherUsageStats = false

[client]
showErrorDetails = "none"

[theme]
base = "light"
primaryColor = "#087F8C"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F2F5F9"
textColor = "#1E2E42"
font = "sans serif"
